### ISSUE TITLE
Feature ideas/to-do

### ISSUE THREAD

**Issue by mrjacobbloom** [notochord/notochord#2]
- [ ] repeats
- [x] playback styles (store with song)
- [ ] volume controls (for individual instruments?)
- [ ] file format for song / import/export

**Comment by mrjacobbloom** [comment]
playback:

- [x] <s>arpeggiation</s> I meant auto <s>gliss</s> but you know what I mean ROLL
- [x] onMeasure/onBeat
- [x] swing
- [ ] more drums (brushes/shakers?)
- listen to actual music when creating styles
- [x] explore 1-indexing for beats?
- [ ] limit available styles by time signature?
- [ ] count in (w/ key?)
